In [1]:
import numpy as np

a = np.array([10,20,30])
b = np.array([40,50,60])
print(a)
print(b)
print(a+b) # it will add and array cannot be comma sepeated 


[10 20 30]
[40 50 60]
[50 70 90]


In [2]:
a = np.array([10,20,"30"])

print(a) # we cannot use mix datatypes 

['10' '20' '30']


In [3]:
a = np.array([10,20,30.])
print(a)

[10. 20. 30.]


In [4]:
l1 = [10,20,30]
l2 = [40,50,60]
print(l1+l2)   # it will cant add they will concenate because we pass as list  

[10, 20, 30, 40, 50, 60]


In [5]:
l1 = [10,20,30]
l2 = 5
print(l1*l2)  # it will mix 5 times 

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]


In [6]:
l3 = [[10,11,22],[44,33,55,66]]
print(l3)

[[10, 11, 22], [44, 33, 55, 66]]


In [7]:
## a = np.array([[10,11,22],[44,33,55,66]])
##print(a) # this show error bcz size is not same 

## Numpy creating array, slicing  and attributes 

In [8]:
import numpy as np

In [9]:
arr = np.array([[11,22,33,44],[55,66,77,88],[12,13,14,15]]) # in array number of each element will same other wise it show error 
print(arr) # this is multi dim array

[[11 22 33 44]
 [55 66 77 88]
 [12 13 14 15]]


In [10]:
print(type(arr)) # checking the type of variable 

<class 'numpy.ndarray'>


In [11]:
# silicing in arrya 
arr1 = np.array([100,200,300,400,500])
print(arr1[0:3])  # if i write like this [0:] it will print all the elemenet  ,, # if i write [3:]  it will print 400 and 500
                   # if i not define and access first three element so like this [:3] it will give me 100,200,300

[100 200 300]


### Attributes 

In [12]:
arr1 = np.array([[100,200,300,400,500],[600,700,800,900,1000],[23,45,56,67,78]])
print(arr1[0:2,0:2]) # multi dim silicing  ## if i write [0:2,0:3] it will show both 3,3, element 
print(arr1[2,3:5])  #[0,1:3] its mean from arry 1 zero is arry one start from 1:3, # if  [1,1:3] it will select 2nd array
print(arr1[2,2])                   # if we acces single element from any array
print(np.shape(arr1))     # it show 3 rowe and 5 column 
print(np.size(arr1))   # tell the  total array element 
print(len(arr1))       # tell the lenth of array they are nested  vlaues 
print(np.ndim(arr1))    # 2 dimensional array rows and column 
print(arr1.dtype)  # to check the datatypes of array. the data present in the array 

[[100 200]
 [600 700]]
[67 78]
56
(3, 5)
15
3
2
int32


### Inspecting an array 

In [13]:
import numpy as np 
a = [50,40,30,20,10]
arr = np.array(a)
print(arr)
print(type(arr))         # datatype of varible 
print(arr.dtype)  
print(arr.astype(float))   # convert the value from int to float  we use astype function 
                           # we can also convert into int to str and also vise  versa 

[50 40 30 20 10]
<class 'numpy.ndarray'>
int32
[50. 40. 30. 20. 10.]


### Mathematical operation and function on array 

In [14]:
import numpy as np
array1 = np.array([30,40,60,20,10])
array2 = np.array([30,20,10,20,20])
print(array1+array2)
print(np.add(array1,array2)) # second method for addition 

[60 60 70 40 30]
[60 60 70 40 30]


In [21]:
import numpy as np
array1 = np.array([[30,40],[20,10]])  # 2D array
array2 = np.array([[30,20],[20,20]])
print(array1+array2)   # operation (+)
print(np.add(array1,array2))     # function (add)

[[60 60]
 [40 30]]
[[60 60]
 [40 30]]


In [15]:
import numpy as np
array1 = np.array([[30,40],[20,10]])  # 2D array
array2 = np.array([[30,20],[20,20]])
print(array1-array2)                   # operation (-)
print(np.subtract(array1,array2))       # function (subtract)

[[  0  20]
 [  0 -10]]
[[  0  20]
 [  0 -10]]


In [16]:
import numpy as np
array1 = np.array([[30,40],[20,10]])  # 2D array
array2 = np.array([[30,20],[20,20]])
print(array1*array2)
print(np.multiply(array1,array2))

[[900 800]
 [400 200]]
[[900 800]
 [400 200]]


In [17]:
import numpy as np
array1 = np.array([[30,40],[20,10]])  # 2D array
array2 = np.array([[30,20],[20,20]])
print(array1/array2)
print(np.divide(array1,array2))

[[1.  2. ]
 [1.  0.5]]
[[1.  2. ]
 [1.  0.5]]


In [18]:
array1 = np.array([3,4,2,1])  # 2D array
array2 = np.array([2])
print(np.power(array1,array2))

[ 9 16  4  1]


In [19]:
arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))


[3. 4. 2. 1.]


###  combining and splitting array

In [20]:
a = [1,2,3]  # in lisr they will mix  but i same operation on aray they will add up 
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [21]:
import numpy as np 
a1 = np.array([11,22,33])
a2 = np.array([44,55,66])
print(np.concatenate([a1,a2]))


[11 22 33 44 55 66]


In [22]:
import numpy as np 
a1 = np.array([[30,40],[50,10]])
a2 = np.array([[5,5],[3,3]])
print(np.hstack([a1,a2]))  # hstack mean horizontal concetnation 

[[30 40  5  5]
 [50 10  3  3]]


In [23]:
import numpy as np 
a1 = np.array([[30,40],[50,10]])
a2 = np.array([[5,5],[3,3]])
print(np.vstack([a1,a2]))    # vertical cotcatenation 

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


## Splitting 

In [28]:
a = np.array([20,40,30,40,10,20])
b = (np.array_split(a,3))  # we will split the array into three part 
print(b[1]) 
print(b)
c = (np.array_split(a,4))  # we will split the array into four part 
print(c)

[30 40]
[array([20, 40]), array([30, 40]), array([10, 20])]
[array([20, 40]), array([30, 40]), array([10]), array([20])]


## Adding and removing element in the arrray 

In [29]:
import numpy as np 
a = np.array([20,40,60,80])
print(np.append(a,90)) # using append method we add an element in the last of the array

[20 40 60 80 90]


In [31]:
import numpy as np 
a = np.array([[20,40],[60,80]]) # using multi dim then first he will convert in to one d array and then append
print(np.append(a,[90,100])) # using append method we add an element in the last of the array


[ 20  40  60  80  90 100]


In [32]:
import numpy as np 
a = np.array([20,40,60,80])
print(np.insert(a,1,50)) # using insert method we add an element in the index number (array,index,value)

[20 50 40 60 80]


In [38]:
import numpy as np 
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60], axis=1)) # if i define axis = 1 it will add like this other wise it show 1d arrray or if i pass axis = 0 is show rows wise

[[20 40]
 [50 60]
 [60 80]]


In [43]:
#print(np.delete(a,1)) # it will delete  from this 

In [46]:
print(np.delete(a,1,axis=0))      # 0 mean rows wise delete and 1 means colunm wise delete the data 

[[20 40]]


In [47]:
print(np.delete(a,1,axis=1)) 

[[20]
 [60]]


## Search, sort, and filter and array 

In [49]:
# sort method 
import numpy as np
ar = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(ar)) # it will sort in ascendinf order 

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [51]:
# search 
import numpy as np
ar = np.array([3,4,1,7,8])
s1 = np.where(ar == 4)
print(s1) # it will seach and tell me the index number where he is located 
s2 = (np.where(ar % 2 == 0))  #that are divisble by 2 
print(s2)

(array([1], dtype=int64),)
(array([1, 4], dtype=int64),)


In [54]:
# using search sort function 
import numpy as np
ar = np.array([1,2,3,4,5])  # using this we have only sorted array 
ss =np.searchsorted(ar,4)
print(ss)

3


In [55]:
# applying filter 
import numpy as np
arr = np.array([20,30,40,50])
fa = [True, False, True,False]
new = arr[fa]
print(new)

[20 40]


In [56]:
# applying filter  secod method 
import numpy as np
arr = np.array([20,30,40,50])
fa = arr>35
new = arr[fa]
print(new)

[40 50]


## Aggregating function in the array  

In [63]:
import numpy as np
arr1 = np.array([20,40,60,70])
print(np.sum(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.size(arr1)) # total number of elemnt 
print(np.mean(arr1))
print(np.cumsum(arr1))  # cumsum is cumalitive sum  20, 40+20=60,20+40+60=120, 20+40+60+70=190
print(np.cumproduct(arr1)) 

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [71]:
a =[ 100,150,199,200,250,130]
b = [10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
print(price,"\n", quantity)
print()
c= np.cumprod([price,quantity],axis=0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

31270


##  Statistical function in array

In [7]:
import numpy as np 
import statistics as stats
baked_food = [200,150,150,130,200,220,170,188]
a = np.array(baked_food)
print(np.mean(baked_food))   # sum of all the values / number of values 
print(np.median(baked_food))   # central values  after sorting
print(stats.mode(baked_food))  # the most re-occured value 
print(np.std(baked_food))
print(np.var(baked_food))  # standard deviation and varience tell the data spread 

176.0
179.0
200
29.017236257093817
842.0


In [8]:
# -1 represent inversly proportional realtionship 
# 1 represent  proportional realtionship 
# 0 represent  no relation 


tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]
print(np.corrcoef([tobacco_consumption, deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]
